"""
Smadex Creative Copilot — Dashboard Builder
============================================
Reads app_data.js and ml_results.json (generated by ml_pipeline_sklearn.py)
and patches them into the existing creative_copilot.html.

Usage:
    python build_dashboard.py
"""

import json
import re
from pathlib import Path

BASE = Path(__file__).parent

# Input files
APP_DATA_JS  = BASE / "app_data.js"
ML_RESULTS   = BASE / "ml_results.json"
TEMPLATE_HTML = BASE / "creative_copilot.html"
OUT_HTML      = BASE / "creative_copilot.html"  # overwrite in place

# ── Validate inputs ──────────────────────────────────────────────────
for f in [APP_DATA_JS, ML_RESULTS, TEMPLATE_HTML]:
    if not f.exists():
        raise FileNotFoundError(
            f"Missing required file: {f}\n"
            "Make sure you ran ml_pipeline_sklearn.py first."
        )

# ── Load generated data ──────────────────────────────────────────────
print("Loading app_data.js …")
app_data_content = APP_DATA_JS.read_text(encoding="utf-8")   # full JS string
print(f"  {len(app_data_content) // 1024} KB")

print("Loading ml_results.json …")
with open(ML_RESULTS, encoding="utf-8") as f:
    ml_obj = json.load(f)
ml_content = "const ML=" + json.dumps(ml_obj, separators=(",", ":")) + ";"
print(f"  {len(ml_content) // 1024} KB")

# ── Load HTML template ───────────────────────────────────────────────
print("Loading HTML template …")
html = TEMPLATE_HTML.read_text(encoding="utf-8")
original_size = len(html)

# ── Patch APP_DATA block ─────────────────────────────────────────────
# The block looks like:  <script>const APP_DATA={...};</script>
pattern_app = re.compile(
    r"(<script>)(const APP_DATA=)(.+?)(;</script>)",
    re.DOTALL
)
if not pattern_app.search(html):
    raise RuntimeError("Could not find 'const APP_DATA=' in the HTML template.")

html = pattern_app.sub(
    lambda m: m.group(1) + app_data_content + m.group(4),
    html,
    count=1
)
print("  ✓ Patched APP_DATA block")

# ── Patch ML block ───────────────────────────────────────────────────
# The block looks like:  <script>const ML={...};</script>
pattern_ml = re.compile(
    r"(<script>)(const ML=)(.+?)(;</script>)",
    re.DOTALL
)
if not pattern_ml.search(html):
    raise RuntimeError("Could not find 'const ML=' in the HTML template.")

html = pattern_ml.sub(
    lambda m: m.group(1) + ml_content + m.group(4),
    html,
    count=1
)
print("  ✓ Patched ML block")

# ── Write output ─────────────────────────────────────────────────────
OUT_HTML.write_text(html, encoding="utf-8")
size_mb = OUT_HTML.stat().st_size / 1024 / 1024
print(f"\n✓ Written: {OUT_HTML}  ({size_mb:.2f} MB)")
print("  Open creative_copilot.html in any modern browser to explore your dashboard.")
