"""
Smadex Creative Copilot - Dashboard Builder
============================================
Reads app_data.js and ml_results.json (generated by ml_pipeline_sklearn.py),
injects the Gemini API key from .env, and builds creative_copilot.html.

Usage:
    python build_dashboard.py
"""

import json
import os
import sys
import getpass
import tempfile
from pathlib import Path

BASE = Path(__file__).parent

APP_DATA_JS   = BASE / "app_data.js"
ML_RESULTS    = BASE / "ml_results.json"
TEMPLATE_HTML = BASE / "dashboard_template.html"
OUT_HTML      = BASE / "creative_copilot.html"
ENV_FILE      = BASE / ".env"


def load_env_key():
    if not ENV_FILE.exists():
        return ""
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        if name.strip() == "GEMINI_API_KEY":
            key = value.strip().strip('"').strip("'")
            return key if key and key != "your-api-key-here" else ""
    return ""


def save_key_to_env(key):
    if ENV_FILE.exists():
        lines = ENV_FILE.read_text(encoding="utf-8").splitlines()
        new_lines, replaced = [], False
        for line in lines:
            if line.strip().startswith("GEMINI_API_KEY"):
                new_lines.append(f"GEMINI_API_KEY={key}")
                replaced = True
            else:
                new_lines.append(line)
        if not replaced:
            new_lines.append(f"GEMINI_API_KEY={key}")
        ENV_FILE.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
    else:
        ENV_FILE.write_text(f"GEMINI_API_KEY={key}\n", encoding="utf-8")


def prompt_for_key():
    print("\n  No valid Gemini API key found in .env")
    print("  Get one free at: https://aistudio.google.com/apikey")
    print("  (Keys start with 'AIza')\n")
    try:
        key = getpass.getpass("  Paste your Gemini API key (or press Enter to skip): ").strip()
    except (EOFError, KeyboardInterrupt):
        key = ""
    if not key:
        print("  Skipped — building without API key. AI features will be disabled.")
        return ""
    if not key.startswith("AIza"):
        print("  Warning: key doesn't look like a Gemini key (expected 'AIza...').")
    save_key_to_env(key)
    print("  Key saved to .env — future runs won't ask again.")
    return key


# ── API key ────────────────────────────────────────────────────────────────
api_key = load_env_key()
if api_key:
    print(f"  API key loaded: {api_key[:10]}{'*'*10}")
    if not api_key.startswith("AIza"):
        print("  Warning: does not look like a Gemini key.")
else:
    api_key = prompt_for_key()
if not api_key:
    print("  Building without API key — AI features disabled.")

# ── Validate inputs ────────────────────────────────────────────────────────
for f in [APP_DATA_JS, ML_RESULTS, TEMPLATE_HTML]:
    if not f.exists():
        print(f"\n  Missing required file: {f}")
        print("  Run ml_pipeline_sklearn.py first.")
        sys.exit(1)

# ── Load data ──────────────────────────────────────────────────────────────
print("\nLoading app_data.js ...")
app_data_content = APP_DATA_JS.read_text(encoding="utf-8")
print(f"  {len(app_data_content) // 1024} KB")

print("Loading ml_results.json ...")
raw_bytes = ML_RESULTS.read_bytes().rstrip(b"\x00")
try:
    ml_obj = json.loads(raw_bytes)
except json.JSONDecodeError:
    text = raw_bytes.decode("utf-8", errors="replace").rstrip().rstrip(",")
    opens  = text.count("{")
    closes = text.count("}")
    if opens > closes:
        text += "}" * (opens - closes)
    try:
        ml_obj = json.loads(text)
        ML_RESULTS.write_text(text, encoding="utf-8")
        print("  Repaired ml_results.json")
    except json.JSONDecodeError as e:
        print(f"  ERROR: cannot parse ml_results.json: {e}")
        sys.exit(1)
ml_content = "const ML=" + json.dumps(ml_obj, separators=(",", ":")) + ";"
print(f"  {len(ml_content) // 1024} KB")

# ── Load template ──────────────────────────────────────────────────────────
print("Loading template ...")
html = TEMPLATE_HTML.read_text(encoding="utf-8")

# Sanitize </script> inside injected data blocks so the HTML parser
# doesn't close the <script> tag prematurely.
app_data_content = app_data_content.replace("</script>", r"<\/script>")
ml_content       = ml_content.replace("</script>", r"<\/script>")

DATA_MARKER = "<script>/** DATA **/</script>"
if DATA_MARKER not in html:
    print("  ERROR: DATA marker missing from template."); sys.exit(1)
html = html.replace(DATA_MARKER, "<script>" + app_data_content + "</script>", 1)
print("  Patched DATA")

ML_MARKER = "<script>/** ML **/</script>"
if ML_MARKER not in html:
    print("  ERROR: ML marker missing from template."); sys.exit(1)
html = html.replace(ML_MARKER, "<script>" + ml_content + "</script>", 1)
print("  Patched ML")

if "%%GEMINI_KEY%%" in html:
    html = html.replace("%%GEMINI_KEY%%", api_key, 1)
    print(f"  API key {'injected' if api_key else 'empty'}")

# Sanity check script tags
opens_count  = html.count("<script")
closes_count = html.count("</script>")
print(f"  Script tags: {opens_count} opens, {closes_count} closes", end="")
if opens_count != closes_count:
    print(" — MISMATCH, aborting"); sys.exit(1)
print(" ✓")

# ── Write: /tmp first, then chunked copy to destination ───────────────────
# Writing 4MB+ directly to a network/OneDrive mount silently truncates.
# Writing to /tmp (local disk) first guarantees integrity.
data     = html.encode("utf-8")
total    = len(data)
tmp_path = Path(tempfile.gettempdir()) / "creative_copilot_build.html"

print(f"\nWriting {total/1024/1024:.2f} MB ...")
with open(tmp_path, "wb") as fh:
    fh.write(data)
if tmp_path.stat().st_size != total:
    print("  ERROR: /tmp write size mismatch"); sys.exit(1)

CHUNK = 65536  # 64 KB — smaller chunks + fsync for VirtioFS reliability
with open(tmp_path, "rb") as src, open(OUT_HTML, "wb") as dst:
    while True:
        chunk = src.read(CHUNK)
        if not chunk:
            break
        dst.write(chunk)
        dst.flush()
    os.fsync(dst.fileno())

written = OUT_HTML.stat().st_size
if written != total:
    print(f"  ERROR: output is {written} bytes, expected {total} — truncated!"); sys.exit(1)

print(f"Built: {OUT_HTML.name}  ({written/1024/1024:.2f} MB)")
print(f"  AI features: {'ENABLED' if api_key else 'DISABLED'}")
print("  Open creative_copilot.html in any modern browser.")
