"""
Smadex Creative Copilot - Dashboard Builder
============================================
Reads app_data.js and ml_results.json (generated by ml_pipeline_sklearn.py),
embeds them into dashboard_template.html, and writes creative_copilot.html.

Gemini API keys are never embedded in the HTML file. Use the Help tab in the
dashboard to save a key in the browser (localStorage only). Optionally set
GEMINI_API_KEY in .env when running ml_pipeline_sklearn.py for cluster personas.

Usage (from the repository root):
    python src/build_dashboard.py
"""

import json
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = Path(__file__).resolve().parent

APP_DATA_JS = REPO_ROOT / "app_data.js"
ML_RESULTS = REPO_ROOT / "ml_results.json"
TEMPLATE_HTML = SRC_DIR / "dashboard_template.html"
OUT_HTML = REPO_ROOT / "creative_copilot.html"

# ── Validate inputs ────────────────────────────────────────────────────────
for f in [APP_DATA_JS, ML_RESULTS, TEMPLATE_HTML]:
    if not f.exists():
        print(f"\n  Missing required file: {f}")
        print("  Run: python src/ml_pipeline_sklearn.py")
        sys.exit(1)

# ── Load data ──────────────────────────────────────────────────────────────
print("\nLoading app_data.js ...")
app_data_content = APP_DATA_JS.read_text(encoding="utf-8")
print(f"  {len(app_data_content) // 1024} KB")

print("Loading ml_results.json ...")
raw_bytes = ML_RESULTS.read_bytes().rstrip(b"\x00")
try:
    ml_obj = json.loads(raw_bytes)
except json.JSONDecodeError:
    text = raw_bytes.decode("utf-8", errors="replace").rstrip().rstrip(",")
    opens = text.count("{")
    closes = text.count("}")
    if opens > closes:
        text += "}" * (opens - closes)
    try:
        ml_obj = json.loads(text)
        ML_RESULTS.write_text(text, encoding="utf-8")
        print("  Repaired ml_results.json")
    except json.JSONDecodeError as e:
        print(f"  ERROR: cannot parse ml_results.json: {e}")
        sys.exit(1)
ml_content = "const ML=" + json.dumps(ml_obj, separators=(",", ":")) + ";"
print(f"  {len(ml_content) // 1024} KB")

# ── Load template ──────────────────────────────────────────────────────────
print("Loading template ...")
html = TEMPLATE_HTML.read_text(encoding="utf-8")

# Sanitize </script> inside injected data blocks so the HTML parser
# doesn't close the <script> tag prematurely.
app_data_content = app_data_content.replace("</script>", r"<\/script>")
ml_content = ml_content.replace("</script>", r"<\/script>")

DATA_MARKER = "<script>/** DATA **/</script>"
if DATA_MARKER not in html:
    print("  ERROR: DATA marker missing from template.")
    sys.exit(1)
html = html.replace(DATA_MARKER, "<script>" + app_data_content + "</script>", 1)
print("  Patched DATA")

ML_MARKER = "<script>/** ML **/</script>"
if ML_MARKER not in html:
    print("  ERROR: ML marker missing from template.")
    sys.exit(1)
html = html.replace(ML_MARKER, "<script>" + ml_content + "</script>", 1)
print("  Patched ML")

if "%%GEMINI_KEY%%" in html:
    html = html.replace("%%GEMINI_KEY%%", "", 1)
    print("  Gemini placeholder left empty (keys stay out of HTML)")

# Sanity check script tags
opens_count = html.count("<script")
closes_count = html.count("</script>")
print(f"  Script tags: {opens_count} opens, {closes_count} closes", end="")
if opens_count != closes_count:
    print(" — MISMATCH, aborting")
    sys.exit(1)
print(" ✓")

# ── Write: temp dir first, then chunked copy to destination ───────────────────
# Writing 4MB+ directly to a network/OneDrive mount silently truncates.
data = html.encode("utf-8")
total = len(data)
tmp_path = Path(tempfile.gettempdir()) / "creative_copilot_build.html"

print(f"\nWriting {total / 1024 / 1024:.2f} MB ...")
with open(tmp_path, "wb") as fh:
    fh.write(data)
if tmp_path.stat().st_size != total:
    print("  ERROR: temp write size mismatch")
    sys.exit(1)

CHUNK = 65536  # 64 KB — smaller chunks + fsync for VirtioFS reliability
with open(tmp_path, "rb") as src, open(OUT_HTML, "wb") as dst:
    while True:
        chunk = src.read(CHUNK)
        if not chunk:
            break
        dst.write(chunk)
        dst.flush()
    os.fsync(dst.fileno())

written = OUT_HTML.stat().st_size
if written != total:
    print(f"  ERROR: output is {written} bytes, expected {total} — truncated!")
    sys.exit(1)

print(f"Built: {OUT_HTML.name}  ({written / 1024 / 1024:.2f} MB)")
print("  Open creative_copilot.html and add your Gemini API key under Help (stored in-browser only).")
